services:
  backend:
    build:
      context: ./backend
    ports:
      - "9091:8080"
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./backend/credentials.json:/app/credentials.json:ro
