services:
  backend:
    build:
      context: ./backend
    ports:
      - "9091:8080"
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./backend/credentials.json:/app/credentials.json:ro
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
