import { ArrowLeft } from 'lucide-react';
import { Button } from '@/app/components/ui/button';

interface TermsOfServiceProps {
  onBack: () => void;
}

export function TermsOfService({ onBack }: TermsOfServiceProps) {
  return (
    <div className="min-h-screen bg-background relative">
      <div className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-14 items-center">
          <Button 
            variant="ghost" 
            size="sm" 
            className="gap-2"
            onClick={onBack}
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Button>
        </div>
      </div>

      <main className="container max-w-3xl py-12 md:py-20 px-6 mx-auto">
        <div className="space-y-8">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tight md:text-4xl">Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: January 14, 2026</p>
          </div>

          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p>
              Welcome to DreamCardAI. By accessing or using our website and services, you agree to be bound by these Terms of Service.
            </p>

            <h3>1. Services Provided</h3>
            <p>
              DreamCardAI provides software tools to assist users in organizing and drafting materials for EB-1 and NIW visa petitions. 
              <strong>We are not a law firm and do not provide legal advice.</strong> Your use of our services does not create an attorney-client relationship.
            </p>

            <h3>2. User Responsibilities</h3>
            <p>
              You are responsible for the accuracy of the information you provide. You agree not to upload false or misleading documents.
            </p>

            <h3>3. Intellectual Property</h3>
            <p>
              The content generated by our platform remains yours. However, the software, design, and underlying technology of DreamCardAI are our exclusive property.
            </p>

            <h3>4. Limitation of Liability</h3>
            <p>
              DreamCardAI is provided "as is." We make no guarantees regarding the outcome of your immigration petition. We are not liable for any rejection or denial of your case.
            </p>

            <h3>5. Termination</h3>
            <p>
              We reserve the right to suspend or terminate your account if you violate these terms.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}